### ISSUE TITLE
idle API 관련하여 문의드립니다. 

### ISSUE THREAD

**Issue by ggy0151** [naver/whale-developers#12]
안녕하세요.
웨일 api중 whale.idle.onStateChanged(function()){}을 사용하려고 하니, 웨일 확장앱 개발자 버전에서 Uncaught TypeError: Cannot read property 'onStateChanged' of undefined
라는 오류가 발생합니다. 이 오류를 어떻게 수정해야 할지 방법을 알 수 있을까요?
그리고 idle을 실행할 경우 background 페이지가 active나 idle인 상태일 때만 돌아가게 할 수 있을까요?

**Comment by kennyd98** [comment]
`manifest.json`에 `idle에 관련한 `permission` 추가하셨나요?
```
 {
        "name": "My extension",
        ...
        "permissions": [
          "idle"
        ],
        ...
      }
```

아래 문서 한번 읽어보시기 바랍니다.
https://developer.chrome.com/extensions/idle

**Comment by ggy0151** [comment]
permission에 idle을 넣어두었는데도, 저런 오류가 발생해서 문의드렸습니다.
다른 해결방안이 있는지 알고 싶습니다.

**Comment by kennyd98** [comment]
`background` 에서 `whale.ide.XXX`을 부른건가요 아니면 `content_script`에서 부른건가요? 작성하신 코드 블럭을 첨부해주세요.

**Comment by laziel** [comment]
콘텐츠 스크립트에서는 whale.idle API 를 사용할 수 없습니다.
백그라운드 스크립트에서 사용해보세요.

https://developers.whale.naver.com/getting_started/anatomy_1/#JS
