### ISSUE TITLE
키보드 단축키 명령이 맥에서는 동작 하지 않는 문제

### ISSUE THREAD

**Issue by pmw9027** [naver/whale-developers#13]
키보드 단축키 기능을 추가하려고 하는데 문제가 생겨서 문의 드립니다.

Popup 을 띄우기 위해서 Manifest 에 "_execute_browser_action" 에 단축키를 등록해놨으나,

윈도우에서는 문제 없이 잘 동작을 하지만 MacOS 에서는 단축키를 눌러도 트리거가 작동하지 않습니다.

동일한 앱을 Chrome extension 으로 동작시 MacOS 에서는 단축키가 작동을 합니다..

Whale Browser 에서는 다른 방법으로 해야되는건가요? 감사합니다.

**Comment by kennyd98** [comment]
단축키를 어떻게 지정하셨는지 `manifest.json` 쪽 설정부분 첨부해주시겠어요?

**Comment by meh9184** [comment]
답변이 늦어서 죄송합니다. 질문자 분이 금일 자리를 비워 제가 대신 답변드리겠습니다!

저희 확장앱의 manifest 파일 링크는 다음과 같습니다. 

[whale_extension-step_tracer/manifest.json](https://github.com/meh9184/whale_extension-step_tracer/blob/master/manifest.json)

**Comment by meh9184** [comment]
답변 감사드립니다!
