### ISSUE TITLE
패키지가 잘못 되었습니다 - 에러

### ISSUE THREAD

**Issue by DoyoungEricaKim** [naver/whale-developers#15]
현재 등록된 앱을 다운로드 받으려하면 "패키지가 잘못 되었습니다. 세부정보: "logo.png"이미지를 디코딩하지 못했습니다.라는 에러 메시지가 나오는데 이미지 파일의 사이즈가 정해진 값이 있어서 에러가 나는 것인지 알고 싶습니다.
업로드 시에는 오류가 나지 않았는데 왜 다운 받을 때 오류가 나는지도 궁금합니다.

**Comment by kennyd98** [comment]
오류가 발생하는 url 공유해주세요.

**Comment by DoyoungEricaKim** [comment]
https://developer.whale.naver.com/detail/mpalnkpcjdaijggoiajkodonieeacnhp
이 사이트 입니다.

**Comment by kennyd98** [comment]
네, 확인해보겠습니다.

**Comment by kennyd98** [comment]
설치가 안되는 문제는 확인하였고요,  웨일 개발자들이 내부적으로 원인을 확인하고 있습니다. 아이콘을 다운사이징하면 우선은 해결되는 듯 합니다. 한번 다시 등록해보시겠어요? 
![logo_128](https://user-images.githubusercontent.com/877691/49717876-caf53c80-fc9b-11e8-91c1-4be3b5a1706e.png)

**Comment by kennyd98** [comment]
https://developers.whale.naver.com/distribution/

**Comment by dyuldyul** [comment]
안녕하세요! 저희도 같은 문제로 에러가 나고 있는데요ㅠㅜ

스토어 등록 시 등록한 아이콘 이미지에는 128*128로 등록을 했지만

매니페스트에 들어가 있는
"icons": {"16": "image/logo_small_paul.png",
        "48": "image/logo_medium_paul.png"},

부분의 "logo_medium_paul.png" 이미지를 디코딩하지 못하였습니다
라는 에러가 나오고 있습니다.

혹시 16에는 160*160 px의 이미지를 등록하고
48에는 480*480 px의 이미지를 등록하면 되는 것일까요?

이미지 사이즈를 어느 정도까지 다운사이징해야되는지 모르겠어 이렇게 문의 드립니다.

답변 주시면 정말 감사하겠습니다.
