### ISSUE TITLE
안녕하세요! 저희도 (패키지가 잘못 되었습니다)로 이미지 디코딩 문제로 에러가 나고 있는데요ㅠㅜ

### ISSUE THREAD

**Issue by dyuldyul** [naver/whale-developers#16]
스토어 등록 시 등록한 아이콘 이미지에는 128*128로 등록을 했지만

매니페스트에 들어가 있는
"icons": {"16": "image/logo_small_paul.png",
        "48": "image/logo_medium_paul.png"},

부분의 "logo_medium_paul.png" 이미지를 디코딩하지 못하였습니다
라는 에러가 나오고 있습니다.

혹시 16에는 160*160 px의 이미지를 등록하고
48에는 480*480 px의 이미지를 등록하면 되는 것일까요?

이미지 사이즈를 어느 정도까지 다운사이징해야되는지 모르겠어 이렇게 문의 드립니다.

해당 url : https://store.whale.naver.com/detail/fdpkbbpgmbpcjjmgokapcfdbablaejmm  입니다.

답변 주시면 정말 감사하겠습니다.

_Originally posted by @dyuldyul in https://github.com/_render_node/MDEyOklzc3VlQ29tbWVudDQ0NjA2NzI4Mw==/timeline/issue_comment#issuecomment-446067283_

**Comment by kennyd98** [comment]
현재 확장앱에 패키징한 아이콘의 이미지가 너무 클 경우 크로미움 내부에서 처리를 못하고 있는 것으로 판단합니다. 웨일 엔진팀에 공유했고 확인중에 있습니다. 

문서에 보면 아래 3가지 아이콘 크기를 권장하고 있습니다. 
https://developer.chrome.com/extensions/manifest/icons
```
"icons": {
    "16": "icon16.png", // 16 x 16
    "48": "icon48.png", // 48 x 48
    "128": "icon128.png"  // 128 x 128
},
```
이 중 128 크기 아이콘은 반드시 추가하셔야 합니다. 이 아이콘 누락시에 확장앱 관리자에 아래와 같이 아이콘 표시가 되질 않습니다. 
![image](https://user-images.githubusercontent.com/877691/49778961-fe42d480-fd4a-11e8-9fdd-152740b4733c.png)

**Comment by dyuldyul** [comment]
아하 네! 알겠습니다~!

답변해주셔서 정말 감사합니다! :D
