### ISSUE TITLE
Possible issue with sidebar-sample

### ISSUE THREAD

**Issue by mjkim610** [naver/whale-developers#2]
환경: 
System OS: OS X 10.11.6
Whale Version: 버전 0.9.34.10 beta (64-bit)

---

`index.html`에서 `index.js`를 호출하지 않는 것 같습니다.

사이드바에서 `setTitle1`, `setBadgeText1`을 클릭해도 버튼이 바뀌지 않습니다.
`index.js`에 문제가 있을까 생각해서 파일의 내용을 변경해봤지만, `index.js`의 아무 코드도 먹히지 않는 것 같습니다.

**Comment by kennyd98** [comment]
확인해보겠습니다. 감사합니다.

**Comment by kennyd98** [comment]
오랫동안 채널 관리가 안되고 있었던 점 죄송하게 생각합니다. 
해당 샘플은 더이상 유지하고 있지 있습니다. 

추후에 다양항 보일러 플레이트를 제공할 예정입니다. 
아래 웨일 개발자 사이트의 샘플코드를 참고해주시기 바랍니다.

https://developers.whale.naver.com/
