### ISSUE TITLE
[질문1]. 개발툴 사용 관련 문의 

### ISSUE THREAD

**Issue by keidiwai** [naver/whale-developers#3]
질문자 : kkbo5222<kkbo5222@naver.com>
질문내용 

사진속의 개발툴을 설치할 수 있는지 궁금합니다.
또한 사진속의 개발툴로 개발할수 있는지도 궁금합니다 !

![screenshot 2018-11-26 at 18 29 40](https://user-images.githubusercontent.com/28287253/49052768-995a8b00-f230-11e8-8af8-51fc5481d846.jpg)

**Comment by kennyd98** [comment]
주소창에 `whale://inspect/#extensions` 입력해보세요~

**Comment by keidiwai** [comment]
@kennyd98  넵 현철님. 제가 메일을 잘못 이해하고, 제가 전달하여 개별 이슈 등록했는데요, 이 친구 다음부터는 개별 등록 해달라고 깃헙 링크 전달할게요 : )
