### ISSUE TITLE
[질문2.] 브라우저 API에 대해 상세 Spec를 기술하는 문서제공 관련 문의

### ISSUE THREAD

**Issue by keidiwai** [naver/whale-developers#4]
질문자 : 이동현 <dlehdanakf@konkuk.ac.kr>
질문내용

---

안녕하세요,

이번 웨일 공모전에서 "Whale loves Pomodoro" 라는 이름으로 프로젝트를 진행하고 있는 이동현 학생입니다.

지난번 멘토링데이 때 조언주셨던 브라우저 API에 대해 상세 Spec를 기술하는 문서를 찾을 수 없어 메일드립니다.

사용자 정보를 저장하는 방법에서 LocalStorage를 사용하기 보다는 웨일 로그인 정보를 기반으로 최대 2MB정도? Sync, 저장이 가능한 Sync Extension을 활용하면 좋을 것 같다고 조언해주셨었습니다.

웨일 개발자 센터에서 whale.storage API는 찾을 수 있지만 Sync Storage 관련된 키워드로는 찾을 수 없어 정확한 API 명칭이 무엇인지 질문드리고 싶습니다!

감사합니다.

**Comment by keidiwai** [comment]
질문자가 개별 등록할 수 있도록 하기위해 해당 이슈는 클로즈 합니다.

**Comment by kennyd98** [comment]
`whale.storage` API 를 얘기한 게 맞습니다.

https://developer.chrome.com/extensions/storage
보시면 `chrome.storage.sync` 랑 `chrome.storage.local` 두가지를 사용할 수 있게 되었는데 ` sync`를 사용하면 계정 동기화 기능을 사용할 수 있어요. 

그리고 저장 용량 제한이 있으니, 구현에 참고하시기 바랍니다. 
https://developer.chrome.com/extensions/storage#property-sync

**Comment by dlehdanakf** [comment]
@kennyd98 위 이슈 질문했던 학생입니다. 콘테스트 담당자 께서 직접 이슈 등록을 유도하셨지만 이미 질문에 답변을 주셔서 댓글 남겨요! 답변 감사드립니다.
