### ISSUE TITLE
사이드바 관련 문의드립니다.

### ISSUE THREAD

**Issue by meh9184** [naver/whale-developers#5]
안녕하세요.

웨일 확장앱 개발 중 문의드리고 싶은 부분이 있어 글을 쓰게 되었습니다. 
질문은 총 2가지 입니다.

* 확장앱에서 상단 툴바 영역과 사이드바 영역에 모두 아이콘을 추가하여 기능을 넣고싶습니다. 혹시 manifest.json 에 browser_action과 sidebar_action을 모두 올릴 수 있는 방법이 있을까요? 만약 현재 제공되는 API로는 가능하지 않다면, 옵션을 추가하여 사용자의 편의대로 2개의 action interface를 변경(switch)하도록 구현하는건 가능할까요??

* 사이드바를 클릭할 경우 생기는 page를 투명하게 하는 방법이 있을까요? 사이드에 생성된 popup 창(용어가 맞는지 모르겠습니다) 밑에 기존에 띄워놓았던 웹 페이지가 보이도록 구현하고 싶은데 현재 제공되는 API로 가능한 부분인지 문의드리고 싶습니다.

바쁘신 중에 문의글 읽어주셔서 감사합니다.

**Comment by kennyd98** [comment]
안녕하세요,

* 안타깝지만 `browser_action`과 `sidebar_action` 두 개를 동시에 사용할 수 없습니다. 하나만 골라서 사용하셔야 합니다. 혹시 어떠한 기능 때문에 두 인터페이스를 동시에 사용하고자 하시는지 공유 가능하다면,  선택을 함께 고민해봐드리겠습니다. 

* 사이드바를 투명하게 하는 방법은 없습니다. [사이드바를 열었다가 닫았다가 하는 방법](https://developers.whale.naver.com/api/sidebarAction/)은 제공됩니다.

```javascript
whale.sidebarAction.show(Integer windowId, Object details, Function callback);
whale.sidebarAction.hide(Integer windowId, Function callback);
```

-  (사이드바열고/닫기가 아닌) 반드시 오버레이로 투명한 사이드바를 구현하고자 하신다면, `content_script`를 활용하여 웹콘텐츠에 사이드바를 구현해보시는 것도 방법입니다. 아래 확장앱을 참고해보세요. 
https://chrome.google.com/webstore/detail/bookmark-sidebar/jdbnofccmhefkmjbkkdkfiicjkgofkdh

**Comment by meh9184** [comment]
답변 감사드립니다!

사실, content_script에 투명한 element를 insert 하여 오버레이시키는 부분은 구현했습니다.

다만 whale 확장 앱 콘테스트인 만큼 sidebar 기능을 이용하여 별도의 popup창 없이 content_script에 메시지를 send 하고 싶었습니다. (상단 툴바 영역의 아이콘이 아닌 사이드바의 아이콘을 클릭하도록 구현하고 싶었습니다.)

하지만 manifest 규격 상 default_page 없이 사이드바를 로드하는 것은 불가능했기 때문에, 기존의 상단 툴바 이이콘을 이용한 접근을 주로 하되 사이드바를 통한 접근은 (popup 창이 생기더라도) 부가로 제공하면 어떨까하여 가능성을 검토하고자 문의 드렸었습니다 ^^

기획 부분에서 더 생각해봐야 할 것 같습니다. 조언해 주신 피드백을 반영하여 개발을 진행해 보겠습니다.
감사합니다 !
