### ISSUE TITLE
안녕하세요 show api에 관하여 궁금한게 있어서 질문드립니다.

### ISSUE THREAD

**Issue by Dailyscat** [naver/whale-developers#7]
안녕하세요 Video Time Marker for YouTube™의 이은규라고 합니다. 

작업 진행 중 show api에 관하여 궁금한게 있어서 문의드립니다.

1. `whale.sidebarAction.show(Integer windowId, Object details, Function callback);`
api의 설명 중 사이드바가 현재 열려있으면 포커스를 옮긴다는 내용을 보았는데요.
`content_script`에서 클릭 등이 발생했을 때 메세지를 extension으로 보내고 위 말씀드린 api를 사용하여
브라우저의 포커스를 extension으로 옮긴 후 extension 내부의 input에 focus를 주려고 했는데요.  브라우저의 포커스가 가질 않아서 그 동작이 실행되질 않습니다.  찾아봤을 때 브라우저에서 다른 브라우저로의 focus 이동은 보안상 되지 않는다는걸 확인은 했는데, 위의 api에서 설명한 focus가 extension이 열린 사이드바 브라우저 자체의 focus를 말하는게 아닌가요?
**show의 callback에서 실행했습니다.

답변 기다리겠습니다. 감사합니다.

**Comment by laziel** [comment]
안녕하세요.

sidebarAction API 동작은 말씀하신 내용대로 동작하는 것이 맞습니다.

사이드바가 열려있는 상태에서 sidebarAction.show() 를 실행하더라도 사이드바 영역에 포커스가 주어지지 않는 현상은 현재 버전(1.3.53.4) 브라우저 버그로 판단되어 수정 예정입니다. 우선 현재 버전에서는 [메시지 교환](https://developers.whale.naver.com/tutorials/messagePassing/#%EC%8A%A4%ED%86%A0%EB%A6%AC%EC%A7%80-API-%ED%99%9C%EC%9A%A9)을 이용하는 방법으로 우회할 수 있습니다.

사이드바가 열려있는지 여부는 사이드바 페이지에서 document.onvisibilitychange 이벤트를 이용하여 확인할 수 있고, 사이드바가 처음 열리는 경우 로딩 시점의 문제로 백그라운드에서 보낸 메시지를 사이드바 페이지에서 받지 못할 수 있는데 이 경우 storage API를 이용하는 우회법이 있습니다. 자세한 내용은 [사이드바앱 만들기](https://developers.whale.naver.com/tutorials/sidebarAction/) 문서를 참조해주세요.

**Comment by Dailyscat** [comment]
감사합니다!
